### ISSUE TITLE
[BUGS] QA bugs found during release

### ISSUE THREAD

**Issue by seaerchin** [isomerpages/isomercms-frontend#1033]
### Problem
this is verbatim from slack 
- [x] most (if not all) skipped tests are due to our new field in Settings - because it’s set as required, it is not backward compatible. hence, all sites that exist now will need to fill this in to enable saving.
- [x] The failing [bug](https://dashboard.cypress.io/projects/nxbty1/runs/104/test-results/baf5d2ef-f5bc-475a-b3fd-374fa793402a)  here (moving resources across resource categories) is a true positive, prob an issue with the the wrong keys being invalidated
- [x] resource pages (resourceCategories.spec) bug: creating resource page of type file does not cause new file to show up until refresh (react-query issue i think), neither does editing page settings
- [x] reordering items do not work due to the `chakra.button` wrapping
- [ ] #1038
- [ ] #1039

**Comment by kishore03109** [comment]
^ hmm am uncomfortable marking this entire issue as closed, let me make the unfixed bugs as separate issues ya

**Comment by seaerchin** [comment]
Wait wtf i think the automation marked this as close HAHAHA
