### ISSUE TITLE
[Feat] allow external link for resource pages

### ISSUE THREAD

**Issue by alexanderleegs** [isomerpages/isomercms-frontend#1046]
We should allow the use of resource pages to external links, as this is something frequently requested by users.
![image](https://user-images.githubusercontent.com/22111124/187885376-95439579-310f-4130-9e21-e28f3810635e.png)

**Comment by alexanderleegs** [comment]
@NatMaeTan 
subtitle: External links must start with https://

**Comment by NatMaeTan** [comment]
Subtitle cleared with Shanty: Enter what you want to link to (e.g. /page-url for pages on your site, or https://www.url.com for external websites)
