### ISSUE TITLE
[BUG] Clicking on manage in the site dashboard does nothing

### ISSUE THREAD

**Issue by seaerchin** [isomerpages/isomercms-frontend#1111]
## Problem
the site dashboard has a `manage` button that should show the collaborators modal when it is clicked. however, it does nothing at present.

## Suggested solution
open the modal

## Definition of done
- modal is open
- users can add/delete etc from the collaborators modal opened through this button

**Comment by dcshzj** [comment]
Should be fixed by #1124.
