### ISSUE TITLE
[BUG] Erroneous last published

### ISSUE THREAD

**Issue by seaerchin** [isomerpages/isomercms-frontend#1112]
## Problem
Currently the `last published by` shown in our site dashboard is determined by the last commit to `staging`. However, this is erroneous as anyone who edits any file after the merge will be shown. 

## Suggested solution
Show the author of the last merge commit to `master` 

## DoD 
(see above)

**Comment by seaerchin** [comment]
should we close this? @dcshzj

**Comment by dcshzj** [comment]
Yup, this is done.
