### ISSUE TITLE
[Feat] Site dashboard for Isomer sites

### ISSUE THREAD

**Issue by dcshzj** [isomerpages/isomercms-frontend#1125]
Tracking tasks for remaining issues to resolve for the site dashboard:

- [x] #1112 (to retrieve merge author from review requests table, currently retrieves the author that made the commit to the master branch, which will be wrong when review requests is used)
- [x] Integrate collaborators modal into the site dashboard (currently done in #1124)
- [ ] Update logic for getting the production URL to retrieve from the launches table first (currently gets from the deployments table, which will be wrong since it will never contain the actual live site that MOPs access)
- [x] Update logic to get the number of new comments not seen by the user (currently no calculation is being done, so will always show as 0 comments)
- [x] Record review request view status (NOT lastViewedAt) when the user accesses the dashboard (currently does not record any view, so it will always show as new review for all users)
- [x] Update merge/close review request backend logic to also delete the review request view statuses (currently does not clean up at all, so the database table can get very large in the future)

**Comment by seaerchin** [comment]
is the third point related to #1109

**Comment by dcshzj** [comment]
Yeah it's related but it's mainly the source of the data. I think #1109 is more of pointing the review request hook to the correct endpoint.

**Comment by seaerchin** [comment]
should we close this? @dcshzj

**Comment by dcshzj** [comment]
Ok sure, I will create a separate issue for item 3 on getting the live URL from the launches DB. That's the only thing left currently, but it's not a functional blocker.
