### ISSUE TITLE
[EditHomepage] Let users know sections are draggable

### ISSUE THREAD

**Issue by kwajiehao** [isomerpages/isomercms-frontend#113]
Currently, the `EditHomepage` side panel allows users to drag and drop sections and have that be reflected on the right display panel. However, there is no sign to users that such a functionality exists. We should add a small display/note/panel/modal to let users know about the drag and drop functionality implemented.

**Comment by gweiying** [comment]
From @NatMaeTan:

> From the usability tests from last year, people managed to figure out on their own that they could drag items around to rearrange them because of the grab cursor. We should save that pro tip space for other important info, also because the UI of the cards are the same across all the pages, once they figure it out for one page they should understand that the behaviour is the same for the others.

Closing since this seems to be a non-issue for now!
