### ISSUE TITLE
Text overflow in homepage preview

### ISSUE THREAD

**Issue by kwajiehao** [isomerpages/isomercms-frontend#146]
Currently, the text in the homepage preview overflows and overlaps with the buttons below (this example taken from the edb-osp-cms-test repo):

<img width="1447" alt="Screenshot 2020-10-08 at 1 54 41 PM" src="https://user-images.githubusercontent.com/31984694/95420452-07fce980-096e-11eb-9a09-e64ca4572edb.png">

Expected behavior: there should be a clean separation between text and buttons

**Comment by alexanderleegs** [comment]
Resolved with https://github.com/isomerpages/isomercms-frontend/pull/172
