### ISSUE TITLE
Automatically log users out when Github access token expires

### ISSUE THREAD

**Issue by kwajiehao** [isomerpages/isomercms-frontend#156]
**Current situation**: When a isomerCMS user's Github access token expires, any actions taken on isomerCMS which require interaction with the Github API (basically any clicking action, since we fetch all of our resources from Github) will fail silently without response

**Expected behavior**: When a user's access token expires, we should log them out automatically and redirect them to the login page. Before logging them out and redirecting them to the login page, we should display a modal which informs them that they are being logged out.

Refer to #142 for more details

**Comment by lisatjide** [comment]
@kwajiehao can we also autosave whatever change they last made before logging them out?

**Comment by kwajiehao** [comment]
@lisatjide there isn't a straightforward way of doing that unless we use a database to save that information. The alternative is local storage on the browser but the notion of autosave is not going to be straightforward to implement, so we'll try to finish our P1s first and then have a look at it again

**Comment by kwajiehao** [comment]
Resolved with #189
