### ISSUE TITLE
Revamp homepage preview

### ISSUE THREAD

**Issue by kwajiehao** [isomerpages/isomercms-frontend#160]
There are currently quite a few problems with the homepage preview. This issue details them and specifies what the fixes should be.

**1. Missing notification bar**
Users should be given the option of adding a notification bar in the homepage. We should provide a **field** for adding the notification bar, and if filled in, that notification bar should be displayed on the homepage preview.

<img width="1387" alt="Screenshot 2020-10-15 at 5 41 56 PM" src="https://user-images.githubusercontent.com/31984694/96106457-d8218900-0f0d-11eb-9631-334a4895939b.png">

**2. `Title` field is ambiguous**
We should rename this field to be `Website title`

<img width="333" alt="Screenshot 2020-10-15 at 5 43 45 PM" src="https://user-images.githubusercontent.com/31984694/96106619-fe472900-0f0d-11eb-9701-c0920fafa9cf.png">

**3. Dropdown element / Highlight subsection within the Hero section should reflect only the title**

For example, in the following image:
<img width="361" alt="Screenshot 2020-10-15 at 5 40 50 PM" src="https://user-images.githubusercontent.com/31984694/96106714-19199d80-0f0e-11eb-9763-2f52e8aa0c6e.png">

The title should just read `Highlight A` instead of `Highlight 1:Highlight A`. This problem occurs for both the dropdown element and the highlight.

**4. "Add a new section" is misleading**
Currently, the "Add a new section" area looks like a button, but does not actually behave like one. We should remove the dotted boundary, the hover state, and left align it to reduce confusion for our users. 

<img width="415" alt="Screenshot 2020-10-15 at 5 47 22 PM" src="https://user-images.githubusercontent.com/31984694/96107054-84636f80-0f0e-11eb-8fc2-56f5c38f9266.png">

Furthermore, we should include an actual button, so that new sections are only added upon click of that button, instead of upon selection of the dropdown option. Currently, we have a bug where we are unable to add two of the same elements in a row (for example, infopic followed by infopic) because the dropdown does not allow us to select two elements consecutively. Adding a button so that the section is added only upon clicking that button would eliminate that bug.

**5. Add a watermark of dummy resource room elements**

Since it's not clear that the resource room elements in the preview are dummy elements and not actually retrieved from the repo, we can make this clearer by adding a watermark/mask over the resource room cards.

<img width="1376" alt="Screenshot 2020-10-15 at 5 50 30 PM" src="https://user-images.githubusercontent.com/31984694/96107531-18cdd200-0f0f-11eb-9123-b5dac729c36f.png">
Add a watermark over the circled area

**6. Remove all hover icons for homepage preview**

Currently, when one hovers over the hero button, or the highlights in the hero section, there is still a white glove hover icon which misleads users into thinking those elements are clickable. We should remove the white glove hover icon for those two elements.

**7. Hint at drag-and-drop functionality for homepage sections**

To do this, replace the white glove hover icon with a 4-directional arrow icon.

**8. Provide default values for homepage sections**

Currently, when a new section is created, the fields are not populated, so users have no idea what a sample layout should look like. We should provide default values and a default image so users know what to do and what field links where.

*Initiation*
<img width="1373" alt="Screenshot 2020-10-15 at 5 55 42 PM" src="https://user-images.githubusercontent.com/31984694/96108085-c6d97c00-0f0f-11eb-8299-6584aad68f74.png">

*With defaults*
<img width="1314" alt="Screenshot 2020-10-15 at 5 58 50 PM" src="https://user-images.githubusercontent.com/31984694/96108400-1a4bca00-0f10-11eb-937c-d1798334c867.png">

**9. Replace image URL with "Choose image" button**
Instead of getting users to type in the URL of an image, we should instead replace this section with a button that asks the user to upload an image instead. Upon clicking this button, they will be redirected to the image upload/selection modal.

<img width="349" alt="Screenshot 2020-10-15 at 5 59 11 PM" src="https://user-images.githubusercontent.com/31984694/96108549-4a936880-0f10-11eb-9d86-55229f0850a1.png">

**Comment by alexanderleegs** [comment]
Resolved with https://github.com/isomerpages/isomercms-frontend/pull/172
