### ISSUE TITLE
Investigate hero subtitle, infopic/infobar description max length

### ISSUE THREAD

**Issue by kwajiehao** [isomerpages/isomercms-frontend#175]
Currently, the max length allowed for hero subtitle, infopic/infobar description is 30 characters, which seems a bit scant. We should check with the designers what the max length should be for these fields.

**Comment by lisatjide** [comment]
Just did a quick check, subtitle max length is still 30. Can we put it at 160 characters? This is a recommended meta descriptions for good SEO
