### ISSUE TITLE
Convert 3rd nav title field to dropdown box in ComponentSettingsModal

### ISSUE THREAD

**Issue by alexanderleegs** [isomerpages/isomercms-frontend#191]
Currently, the 3rd nav title is left as a text field. Ideally, we would like to be able to provide a list of existing 3rd nav titles for the user to choose from, but the 3rd nav title field is stored only in the front matter of each file. To obtain the full list, we would need to look through all files in the directory, which is inefficient. One way we could explore to do this is using bluebird to make those calls concurrently, although this might still be slow.

**Comment by kwajiehao** [comment]
We're already retrieving all page content to generate the accordion left nav when editing collection pages (refer to PR #178), so what we could perhaps do is to extract the data fetching to the collection layer and pass page content as props to each `EditPage` instance

**Comment by kwajiehao** [comment]
Resolved with #218
