### ISSUE TITLE
Third nav page: Title on listing, page preview are not consistent with editpage modal

### ISSUE THREAD

**Issue by lisatjide** [isomerpages/isomercms-frontend#192]
The title displayed on 
- Page listing
- Page preview
- Edit page modal
should be consistent to avoid confusion.

**Title of page preview**
![Screenshot 2020-11-02 at 5 31 02 PM](https://user-images.githubusercontent.com/23736580/97852164-59ac5000-1d31-11eb-93f4-c0db259a15d4.png)
**Title on page listing**
![Screenshot 2020-11-02 at 5 30 55 PM](https://user-images.githubusercontent.com/23736580/97852231-6f217a00-1d31-11eb-88e0-95307d827e0f.png)
**Title on edit page modal - does not have number in front**
![Screenshot 2020-11-02 at 5 30 46 PM](https://user-images.githubusercontent.com/23736580/97852173-5e710400-1d31-11eb-8ec0-5119cbf8d7df.png)

**Comment by kwajiehao** [comment]
No longer a problem
