### ISSUE TITLE
Upload image not working on homepage

### ISSUE THREAD

**Issue by lisatjide** [isomerpages/isomercms-frontend#196]
There should be an additional modal, see below
<img width="981" alt="Screenshot 2020-11-03 at 3 05 52 PM" src="https://user-images.githubusercontent.com/23736580/97957417-12cc6200-1de6-11eb-8ef7-7c90feea2560.png">

**Comment by alexanderleegs** [comment]
Resolved in https://github.com/isomerpages/isomercms-frontend/pull/197
