### ISSUE TITLE
Add unsaved changes warning modal before user leaves on homepage, leftnav page, posts, and settings

### ISSUE THREAD

**Issue by lisatjide** [isomerpages/isomercms-frontend#220]
Currently the save change modal will be prompted only on simple pages.
<img width="936" alt="Screenshot 2020-11-12 at 3 53 28 PM" src="https://user-images.githubusercontent.com/23736580/98911226-36d32600-24ff-11eb-87f5-d7633c0de990.png">

This warning should also be prompted in the following pages when any changes are done:
1. Pages within a collection
2. Homepage
3. Posts in resources
4. Settings, if possible

**Comment by alexanderleegs** [comment]
Collection pages: https://github.com/isomerpages/isomercms-frontend/pull/170
Homepage warning: https://github.com/isomerpages/isomercms-frontend/pull/230
Resource posts: https://github.com/isomerpages/isomercms-frontend/pull/170
Settings warning: https://github.com/isomerpages/isomercms-frontend/pull/288
