### ISSUE TITLE
Misc. issues for `ComponentSettingsModal`

### ISSUE THREAD

**Issue by kwajiehao** [isomerpages/isomercms-frontend#234]
### ~1. Sanitize Title field input to prevent HTML input~
Canceled since React sanitizes input for us

### 2. Validation of category folder name
- Only allow alphanumeric characters with `-` (dash)
- Convert to lowercase on submission

### 3. Validation of third nav section name
- Only allow alphanumeric characters and space
- Convert to lowercase on submission

### ~4. Permalink~ Superceded by #255
~- Make category folder name lowercase~
~- Slugify third nav section name and make lowercase~

### 5. When creating a new collection, also update `navigation.yml` to include the new collection
- This is an update to the backend endpoint
- Deslugify the collection name to come up with the collection title when writing to `navigation.yml`

**Comment by alexanderleegs** [comment]
Point 4 (permalink) is superseded by https://github.com/isomerpages/isomercms-frontend/issues/255, given that we no longer want to enforce permalink prefixes
