### ISSUE TITLE
Page-moving modal position

### ISSUE THREAD

**Issue by kwajiehao** [isomerpages/isomercms-frontend#243]
If the page-moving modal is opened on the right-most card, it forces the body to overflow horizontally and to scroll horizontally.

<img width="1675" alt="Screenshot 2020-11-19 at 12 56 27 PM" src="https://user-images.githubusercontent.com/31984694/99623279-b5cbdf80-2a66-11eb-950b-edba43031b90.png">

We should **not** allow overflow and instead force the modal to go backwards towards the left (flip towards the left instead of to the right)

**Comment by alexanderleegs** [comment]
Opening the page-moving modal on any of the bottom row items also shifts the entire body upwards
