### ISSUE TITLE
[feat] Image modal alt-text

### ISSUE THREAD

**Issue by gweiying** [isomerpages/isomercms-frontend#283]
This issue record details of all past discussions for the alt-text image modal, so that we can continue work in February after hackathon.

## Goal
We want to introduce a modal for users to enter alt-text for images on the CMS when they embed an image on a page.

The modal will look as follows:
<img width="1406" alt="Screenshot 2020-12-07 at 2 35 26 PM" src="https://user-images.githubusercontent.com/39231249/101357222-73ddce80-3899-11eb-966a-7f735dc33a85.png">
The `File Name` field will be editable/ greyed out, depending on where the user has accessed this modal from (details on this below). Note that this modal looks visually very similar to the "Edit Image" modal that appears when a user uploads an image from the Images tab, but no `Alt Text` field is present when the user accesses the "Edit Image" modal via Images tab. 

### Consistency in user experience across places where "Insert Image" alt-text modal should appear

The "Insert Image" alt text modal will appear in 4 scenarios: 
1. Edit Page (after user selects an image for upload via MDE Image button > Select Image> Upload file)
2. Edit Page (after user selects image from library via MDE Image button > Select Image)
3. Edit Homepage (infopic, hero section, after user selects an image for upload via Choose Image button > Select Image > Upload file)
4. Edit Homepage (infopic, hero section, after user selects an image from library via Choose Image button > Select Image)

The overall behavior of the modal should be kept consistent across all 4 scenarios. Specific details are detailed below:
- In 1., 3., the user will be allowed to edit both the `File Name` and the `Alt Text` field since it is a new file that they have uploaded. 
- In 2., 4., since the user has selected an existing image from the library, the `File Name` field should be greyed out, with a blue note below that specifies "File names can be changed under the Images tab"
- In 3., 4., the current field for alt text should be revamped. When no image is selected, the alt-text button is greyed out. When an image is selected, a preview of the alt-text is available, and the alt-text button opens up the "Insert Image" modal. If a user selects the Choose image button, the button opens up the "Select Image" modal.   See next two images: <img width="370" alt="Screenshot 2020-12-07 at 9 49 29 AM" src="https://user-images.githubusercontent.com/39231249/101329304-8217f480-3871-11eb-87ce-d0303c86b02f.png"> 
(before) <img width="1305" alt="Screenshot 2020-12-07 at 9 49 05 AM" src="https://user-images.githubusercontent.com/39231249/101329268-74626f00-3871-11eb-8dc2-b7e461565c10.png"> (after)

### Components for image related modals are reused in many places

The components for image-related modals are reused in many places and also shared with other types of media files. Care should be exercised that new changes to any modals should not affect any existing functionality. Here's an outline of where all image-related modals are used, along with a short description of what they are and where they are used:

1. Select Image modal (`MediaModal.jsx`): displays current library of images shown as cards, as well as an upload card. Modal is shown on **Edit Page**, **Edit Homepage** - hero section, infopic and **Settings** - favicon, shareicon, agency logo <img width="1247" alt="Screenshot 2020-12-07 at 2 41 58 PM" src="https://user-images.githubusercontent.com/39231249/101357887-5e1cd900-389a-11eb-8932-988081a39409.png">
2. Insert Image modal (?): displays image, file name and alt-text fields. Modal is shown after user has selected an image for inserting via Select Image modal. If user uploads a new image, file name field is editable, else if user selects an existing image in the library, file name is not editable. Modal is only shown after **Edit Page**, **Edit Homepage**'s Select Image modal as images selected via Select Image modal in **Settings** do not allow for alt text currently <img width="1406" alt="Screenshot 2020-12-07 at 2 35 26 PM" src="https://user-images.githubusercontent.com/39231249/101357222-73ddce80-3899-11eb-966a-7f735dc33a85.png">
3. Edit Image modal (`MediaSettingsModal.jsx`): displays image, file name. Modal is shown after user has selected an image for editing via the **Images tab** <img width="930" alt="Screenshot 2020-12-07 at 4 02 08 PM" src="https://user-images.githubusercontent.com/39231249/101366709-90800380-38a5-11eb-8d0c-ca1dc755805d.png">

Overall, just one new modal is introduced, the Insert Image modal for alt-text, which riffs on the existing Edit Image modal. However, to specify rules on when which modal (Insert Image vs Edit Image) should be used can be challenging because images and other medias use the same components for Selecting, Uploading and Editing and image, but other medias types will never require the "Insert Image" alt-text modal. In particular, we have to figure out how to set cases in `FormFieldMedia.jsx`/ create a new custom component that supports the extra checks for images.

### Other changes

- Alt-text placeholder field should be: "Describe your image to improve accessibility"
- On Select Image modal, remove "Select Image button". Clicking on an image should automatically transition to the next modal: Insert Image modal. Transition to next modal should not cause two layers of greyed out background to stack). Next modal should be same width as Select Image modal.
- On Insert Image modal (in Edit Page, Edit Homepage), Close will close everything, Cancel will go back to Select Image modal, Select will close everything and save
- Rename "Edit Image" modal from Images tab to "Image Details"
- Behavior of image selection on Settings page should also ask for alt-text for consistency, but this is P3.

**Comment by lisatjide** [comment]
wow, can I just say that this is a super comprehensive issue. great job @gweiying!

**Comment by gweiying** [comment]
Partially completed in EditPage modals, but not in EditXX pages. Changes to be completed as part of EditXX refactors over the next Q1.

![Screenshot 2022-02-08 at 10 34 04 AM](https://user-images.githubusercontent.com/39231249/152906988-21c65477-3037-4136-ac44-2a50ca05c8b6.png)

**Comment by gweiying** [comment]
Deprioritised until after we move to OGP design system components. Since the functionality to add alt text already exists in EditXX pages, we will not build custom components for now.
