### ISSUE TITLE
Bug: Chinese characters or other languages in page title

### ISSUE THREAD

**Issue by kwajiehao** [isomerpages/isomercms-frontend#293]
**Problem**
When saving resource files / pages with titles in Chinese, we attempt to slugify and write the filename in chinese, but it comes out as a gibberish string like “abcdaeuireia-acajcajc.md”

**Solution**
None so far, to be discussed with designers.

**Comment by kathleenkhy** [comment]
@alexanderleegs @gweiying has this been fixed alr? thanks!

**Comment by alexanderleegs** [comment]
Fixed with the refactor - foreign characters fully supported now for page titles
