### ISSUE TITLE
Misc. UI Bugs

### ISSUE THREAD

**Issue by kwajiehao** [isomerpages/isomercms-frontend#302]
This issue documents miscellaneous UI bugs that we should fix before pushing to production:

#### `Settings` layout
- Image fields - when an image field in the `Settings` page is updated, display a success toast
- Make the “Save” button a floating one (by setting its position to `fixed`)

#### Fix `Images` layout bug (refer to image below)**
<img width="1072" alt="Screenshot 2020-12-21 at 3 40 32 PM" src="https://user-images.githubusercontent.com/31984694/102758348-98fc3200-43ad-11eb-8a8d-4834133d0952.png">

- This occurs when the images folder does not exist in a repo.

#### `EditHomepage`
- Make the dropdown chevron more clickable (the entire right side of the element - highlighted in orange - instead of just the area around the chevron)

<img width="424" alt="Screenshot 2020-12-21 at 5 09 07 PM" src="https://user-images.githubusercontent.com/31984694/102759607-4d4a8800-43af-11eb-9866-0de0023970a1.png">

**Comment by alexanderleegs** [comment]
All issues here have been resolved by https://github.com/isomerpages/isomercms-frontend/pull/305 except the fixed save button.
