### ISSUE TITLE
Image/file retrieval for subdirectories

### ISSUE THREAD

**Issue by alexanderleegs** [isomerpages/isomercms-frontend#310]
Currently, some sites have subdirectories for their images (e.g. https://github.com/isomerpages/mof-vital). Our current method for retrieving images only returns top level images, and any images in subdirectories are not retrieve. We should correct this behaviour to retrieve images recursively, and also make this change for files.

**Comment by gweiying** [comment]
Unassigning myself: discussed with Alex and this issue is fairly complicated because we would also then have to support deleting, saving to other subdirectories, and other associated navigations.

**Comment by gweiying** [comment]
Another site affected by this: https://github.com/isomerpages/ncss-ssi/tree/staging/images

**Comment by kwajiehao** [comment]
To be looked at after CMS navigation is done
