### ISSUE TITLE
Image src links don't work for private repos

### ISSUE THREAD

**Issue by kwajiehao** [isomerpages/isomercms-frontend#367]
When we display images on the CMS, we include a link to the raw file from GitHub (for example: `https://raw.githubusercontent.com/isomerpages/<repo name>/staging/images/<image name>`

<img width="1669" alt="Screenshot 2021-03-04 at 11 47 41 AM" src="https://user-images.githubusercontent.com/31984694/109908599-88d2ce00-7cdf-11eb-8fef-09acccc5680b.png">

However, this doesn't work for private repos, as GitHub does not allow linking without a token (the correct URL will be of the form: `https://raw.githubusercontent.com/isomerpages/<repo name>/staging/images/<image name>?token=<random token>`). As such, we get `404` errors when we link in the usual way:
<img width="1618" alt="Screenshot 2021-03-04 at 11 35 28 AM" src="https://user-images.githubusercontent.com/31984694/109908685-a7d16000-7cdf-11eb-8964-dda19b71c54c.png">

Since private repos are few in number, this issue is not a priority. However, we should still fix this once we're done with all outstanding issues.

**Comment by gweiying** [comment]
Closed with https://github.com/isomerpages/isomercms-frontend/pull/473
