### ISSUE TITLE
UX: should items render asynchronously?

### ISSUE THREAD

**Issue by kwajiehao** [isomerpages/isomercms-frontend#368]
### Description

Currently, our layouts render asynchronously. The layout where this is most obvious is the `Workspace` layout, where we first check for the existence of the `Contact Us` page before rendering it, and then for collections before rendering those, and finally for unlinked pages. Is it better for all these elements to appear one-by-one, or all-at-once?

**Comment by prestonlimlianjie** [comment]
To explore later - not a significant problem that we want to devote design/eng resources to now
