### ISSUE TITLE
[enhancement] render Html Components for preview in EditNavBar

### ISSUE THREAD

**Issue by gweiying** [isomerpages/isomercms-frontend#404]
Html components such as images will not work on our EditNavBar preview.

We can consider investigating how much effort it will take to display html components on our EditNavBar. One possibility is using `dangerouslySetInnerHtml`, like how we do in SimplePage.

<img width="1792" alt="Screenshot 2021-04-12 at 6 07 04 PM" src="https://user-images.githubusercontent.com/39231249/114378058-e6e5b180-9bb9-11eb-8b9a-7201840bfe54.png">

**Comment by prestonlimlianjie** [comment]
We probably won't ever need images in our nav bar, so we can shelve this for now
