### ISSUE TITLE
Refactor: create a single ApiClient instance to handle all API calls from the frontend

### ISSUE THREAD

**Issue by prestonlimlianjie** [isomerpages/isomercms-frontend#429]
### Problem
We currently create new axios instances each time we make an API call to the backend. This is not ideal because of the following:
- We re-define the `baseUrl` each time, and as such, we have to edit all instances when we need to modify the `baseUrl`. This is also why our `REACT_APP_BACKEND_URL` env var looks like `<BACKEND_URL>/v1` - because it was a hassle to modify all axios instances to include that new `/v1` path when we edited our backend API endpoints.
- The axios configurations are peppered across the codebase. For example, the interceptor configuration is in `App.jsx`, and we have `axios.defaults.withCredentials = true` in all of our Component files.

### Solution
Create a single ApiClient that is based on one single axios instance (created using `axios.create`)

**Comment by gweiying** [comment]
Done here: https://github.com/isomerpages/isomercms-frontend/blob/9239553e6044e0932f208594de076bc074211490/src/App.jsx#L40-L44
