### ISSUE TITLE
Refactor MediaSettingsModal

### ISSUE THREAD

**Issue by alexanderleegs** [isomerpages/isomercms-frontend#445]
Renaming/deleting images or files currently has inconsistent behaviour - it refreshes the page on completion, instead of refetching, which is the case for most other operations. The reason for this is that MediaSettingsModal is still a class component - we should refactor this to make it a functional component, as well as introduce react-query, in order to bring it up to date with our other components.

**Comment by gweiying** [comment]
Closed with #415, #416
