### ISSUE TITLE
[feat] Move functionality for medias

### ISSUE THREAD

**Issue by gweiying** [isomerpages/isomercms-frontend#452]
Right now, users have no way to move images or files between folders. To make the nested medias functionality complete, we should support media-moving, so that users will not need to go to Github to move their media.

Link to [Figma design file](https://www.figma.com/file/4qNhGTBMs521pDvCAIh4ON/IsomerCMS?node-id=1024%3A8585)

**Comment by alexanderleegs** [comment]
This should also include the movement of images/files into a newly created subfolder, similar to what is being done in collections.
