### ISSUE TITLE
[feat] Show preview of custom colors in Settings

### ISSUE THREAD

**Issue by gweiying** [isomerpages/isomercms-frontend#457]
Right now when users update their primary, secondary and other colors via the Settings page, it is not clear to them how these colors changes will affect their site as there's no preview mechanism for users.

To rectify this, we should show a sample preview for users on how their colors settings will be reflected on their site.

**Comment by lisatjide** [comment]
this could have been addressed by user clicking the **view staging** button

**Comment by prestonlimlianjie** [comment]
Issue is stale - will revisit if necessary via the CMS redesign
