### ISSUE TITLE
Build minutes for websites on netlify

### ISSUE THREAD

**Issue by alexanderleegs** [isomerpages/isomercms-frontend#466]
Currently, we use quite a lot of build minutes on small changes - we should look into ways to extending the time window for skipping builds if many changes are being made at once.

In addition, we should also consider removing build previews for agency websites, if most agencies do not use this feature.

**Comment by prestonlimlianjie** [comment]
Not an issue anymore since we upgraded to enterprise. We can revisit removing build previews later.
