### ISSUE TITLE
announcement modal/banner

### ISSUE THREAD

**Issue by lisatjide** [isomerpages/isomercms-frontend#482]
EDIT:

To kickstart this with Modal for Identity Phase 1

------

As we roll out more features and fixes, announcement modal or banner will be used to keep users informed about these changes. 

Types of announcements:
1. Important and requires their attention - this should stays throughout the entire CMS screens and user will not be able to dismiss it. Important for announcement such as stopping support of certain feature etc
2. New features announcement 
3. Bug fixes

examples below
<img width="432" alt="Screenshot 2021-05-25 at 9 48 54 AM" src="https://user-images.githubusercontent.com/23736580/119427890-7ac0a680-bd3e-11eb-984c-3c99b873a27c.png">
<img width="1280" alt="Screenshot 2021-05-25 at 9 49 32 AM" src="https://user-images.githubusercontent.com/23736580/119427902-83b17800-bd3e-11eb-97ad-19662e008d33.png">

[this is an ongoing issue, please add in more comments if necessary]

**Comment by NatMaeTan** [comment]
Refer to [here](https://docs.google.com/presentation/d/1NjbrcijcMqYAc0LSYGUASfvykPBIeVorpnfuqDZSDtU/edit?usp=sharing) for a comparison of the different methods to make an announcement.

**Comment by lisatjide** [comment]
To start with an announcement modal first. to explore notification bell in the future. 
Separately, bug fixes announcement to be moved to CMS guide.

**Comment by kathleenkhy** [comment]
this will be catered for under #772
