### ISSUE TITLE
[bug] Delete file modal shows 'Delete image'

### ISSUE THREAD

**Issue by prestonlimlianjie** [isomerpages/isomercms-frontend#507]
<img width="1552" alt="Screenshot 2021-06-08 at 12 05 30 PM" src="https://user-images.githubusercontent.com/19917616/121121295-e6803480-c851-11eb-9e34-9d37f793a83d.png">

**Comment by gweiying** [comment]
Fixed in current develop branch

![Screenshot 2022-02-08 at 10 31 14 AM](https://user-images.githubusercontent.com/39231249/152906683-22f93cbf-4689-493f-bb40-8baf23d1f78e.png)
