### ISSUE TITLE
test: clean up of EditPage test spec

### ISSUE THREAD

**Issue by kwajiehao** [isomerpages/isomercms-frontend#526]
The EditPage test spec adds a file `ADDED_FILE_TITLE` (currently set to "editpage_placeholder_add.txt") which affects downstream tests in the Files spec.

We should fix this by either:
- Cleaning up after the EditPage spec by deleting this file after all EditPage tests are completed
- Reset the repo state before each test spec
- Make our tests less flaky by using more resilient selectors (for example, instead of searching for `[id^="${newMediaFolder}-1"]` we could instead use a `data-cy` attribute and search for that instead)

**Comment by prestonlimlianjie** [comment]
Not as crucial now since we reset the entire repo before running tests. Might revisit later.
