### ISSUE TITLE
Settings page does not work if repo has no social_media links

### ISSUE THREAD

**Issue by alexanderleegs** [isomerpages/isomercms-frontend#529]
Currently, we attempt to retrieve the social media content from the retrieved footer as follows:
```
socialMediaContent: {
    facebook: footerContent.social_media.facebook,
    twitter: footerContent.social_media.twitter,
    youtube: footerContent.social_media.youtube,
    instagram: footerContent.social_media.instagram,
    linkedin: footerContent.social_media.linkedin,
},
```

However, this causes an error when no social_media field exists in the footer file. We should add a check for the existence of the social_media field when retrieving data.

**Comment by gweiying** [comment]
closed by https://github.com/isomerpages/isomercms-frontend/pull/496
