### ISSUE TITLE
URI Encoding

### ISSUE THREAD

**Issue by lisatjide** [isomerpages/isomercms-frontend#530]
**Problem**
All titles with special characters are slugified, meaning it the special characters will be automatically removed for the user. 

**Proposed solution**
Implement URI encoding to supporting special characters (symbols like # or ! and foreign language) for **collection** name.

**Comment by kathleenkhy** [comment]
@alexanderleegs @gweiying has this been done? Is this related to #531 ?

**Comment by alexanderleegs** [comment]
Fixed as part of the refactor!
