### ISSUE TITLE
Display special characters on subfolder, page title and preview

### ISSUE THREAD

**Issue by lisatjide** [isomerpages/isomercms-frontend#531]
**What is the current problem**
Currently when user creates a page with special characters, the CMS will auto slugify the display names at the following locations: 
- Subfolder
- Page title 
- Previews. 
This behavior does not occur on the actual staging site. 

**Proposed Solution**
To fix this issue by displaying special characters on all 3 places listed above, this means not slugifying the titles and allow special characters in file names.

**Comment by lisatjide** [comment]
Related issue https://github.com/isomerpages/isomercms-frontend/pull/322

**Comment by kathleenkhy** [comment]
@alexanderleegs @gweiying do we know if this has been done alr?

**Comment by alexanderleegs** [comment]
Fixed as part of the refactor!
