### ISSUE TITLE
[Refactor] Refactor modals so they use the same code / enhance modals

### ISSUE THREAD

**Issue by kwajiehao** [isomerpages/isomercms-frontend#54]
We can refactor all modals (`PageSettingsModal`, `ResourceCategoryModal`, `ResourceSettingsModal`) to use the same code.

Other enhancements include:
- add an onKeyDown so that if people click the `Esc` button while the modal is active we toggle settingsToggle so that the modal is deactivated

**Comment by gweiying** [comment]
Replaced by #794
