### ISSUE TITLE
meta description, image, title on setting page

### ISSUE THREAD

**Issue by lisatjide** [isomerpages/isomercms-frontend#578]
currently agencies can modify their meta description, title and image on the config file. 
This will reflect in the preview of their site on google search and also when the site URL is shared on social media platforms. 

These fields should also be made available on the CMS so agencies can do it themselves without getting isomer team's involvement.

**Comment by kathleenkhy** [comment]
Is this still valid? Seems like this might happen if users tamper with github directly?

**Comment by kathleenkhy** [comment]
This has already been done - pls jump in if I'm wrong @alexanderleegs @gweiying
