### ISSUE TITLE
[Refactor] CollectionPages flow refactor

### ISSUE THREAD

**Issue by prestonlimlianjie** [isomerpages/isomercms-frontend#601]
The CollectionPages refactor cleans up the frontend code (sets up the API client and PageService layer, and cleans up the EditPageV2 layout for Collection Pages)

PRs:
- https://github.com/isomerpages/isomercms-frontend/pull/590
- https://github.com/isomerpages/isomercms-frontend/pull/598
- https://github.com/isomerpages/isomercms-frontend/pull/599

**Comment by gweiying** [comment]
Closed with #603
