### ISSUE TITLE
Add a frontend check for file upload size and display error message to user

### ISSUE THREAD

**Issue by prestonlimlianjie** [isomerpages/isomercms-frontend#621]
Currently, when a user uploads a file/document that is larger than 10MB, the frontend proceeds to send the file to the backend. However, the backend EB has been configured to reject files > 10MB; the user has to wait a long time to realize that their file is too big.

We can use the [File API on the browser](https://developer.mozilla.org/en-US/docs/Web/API/File/size) to figure out if the file is too big and give feedback sooner.

**Comment by gweiying** [comment]
Completed in Media Refactor
