### ISSUE TITLE
[Design System] Migrate existing Footer to ChakraUI

### ISSUE THREAD

**Issue by seaerchin** [isomerpages/isomercms-frontend#861]
**work required**
isomer's current `Footer` component is a thin wrapper over 2 buttons; this could be better written using layout components from ChakraUI and pulling some state downwards into the component itself (eg: fix the text labels on buttons; always have 2 buttons on `Footer`) 

This component could either be inlined into its relevant call-sites or to be refactored and presented with a simpler API

Refer to the base figma [here](https://www.figma.com/file/7OtNYkc4s9BkFk05ConEbd/V1.5?node-id=285%3A23615) and an example of the use case [here](https://www.figma.com/file/7OtNYkc4s9BkFk05ConEbd/V1.5?node-id=269%3A30764). Note that the use case lacks the cancel button.

Also, do followup with the designers if it should be a `ButtonGroup` or two separate `Buttons` (eg: if loading -> both load?)

Do also take note that the existing `.sectionFooter/pageEditor` css class **should be replaced** (might have to seek @NatMaeTan for design input here)

**Comment by seaerchin** [comment]
this issue is tangentially solved by the mentioned PR/commits - the component is using chakra UI right now but some components have a `div` wrapping that makes it look like a footer; we have to iron those out

**Comment by NatMaeTan** [comment]
> Also, do followup with the designers if it should be a ButtonGroup or two separate Buttons (eg: if loading -> both load?)

Should be a button group, only 1 button loads at a time

> Do also take note that the existing .sectionFooter/pageEditor css class should be replaced (might have to seek @NatMaeTan for design input here)
Lmk what you'd need
