### ISSUE TITLE
[FEATURE] Allow users to update resource name

### ISSUE THREAD

**Issue by seaerchin** [isomerpages/isomercms-frontend#943]
### Problem
currently, users are not able to update resource room name by themselves, which results in them having to email isomer support to do this change.

this results in increased ops workload for prod support

### Suggested solution
1. add a modal similar to the existing one to update directory title

**Comment by seaerchin** [comment]
@NatMaeTan any ideas for design or should i just reuse the existing modal

**Comment by NatMaeTan** [comment]
Reuse the existing modal for like page settings, just with 1 field!
